name: Sync Fork

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set Upstream
        run: |
          git remote add upstream https://github.com/fractal-bootcamp/snack-safari.git
          git fetch upstream

      - name: Sync with Upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
